server:
  port: 8086

spring:
  datasource:
    #    Временно postgres сделаем, потом поменяем
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:dbchangelog-master.xml
    drop-first: false

jwt:
  expiration: 60480000