server:
  port: 8086
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:dbchangelog-master.xml
    drop-first: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  header: Authorization
  secret: token
  expiration: 60480000
social_network:
  main_link: ${MAIN_LINK}
cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true